version: '3.9'

networks:
  microservices-net:

volumes:
  keycloak-datastore:
  mongo_data:

services:
  keycloak-db:
    image: postgres:10.10
    volumes:
      - keycloak-datastore:/var/lib/postresql/data
    networks:
      - microservices-net
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB:       keycloak
      POSTGRES_USER:     keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    extra_hosts: ['host.docker.internal:host-gateway']
    depends_on:
      - keycloak-db
    networks:
      - microservices-net
    ports:
      - "8180:8080"
      - "8686:8686"
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    environment:
      KC_DB:   postgres
      KC_DB_URL_HOST:     keycloak-db
      KC_DB_URL_PORT:     5432
      KC_DB_USERNAME:     keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN:     microservice_admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      #KC_HTTP_PORT: 8180
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_LOG_GELF_LEVEL: INFO
      KC_LOG_LEVEL: INFO
      JAVA_OPTS: -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8686,server=y,suspend=n
    command:
      - start-dev
      - --import-realm
  mongodb:
    image: mongo:latest
    restart: always
    extra_hosts: ['host.docker.internal:host-gateway']
    networks:
        - microservices-net
    ports:
        - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: mongoadmin
        MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./docker/mongoentrypoint/:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    command: [--auth]
  mongo-express:
    image: mongo-express:latest
    restart: always
    extra_hosts: ['host.docker.internal:host-gateway']
    networks:
        - microservices-net
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:secret@mongodb:27017/
  tempo:
    image: grafana/tempo
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks: 
        - microservices-net
    volumes:
        - ./docker/tempo/tempo-local.yaml:/etc/tempo.yaml:ro
        - ./tempo-data:/tmp/tempo
    ports:
        - "14268"  # jaeger ingest
        - "9411:9411" # zipkin
        - "3200:3200"
  loki:
    image: grafana/loki
    extra_hosts: ['host.docker.internal:host-gateway']
    networks: 
        - microservices-net
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
        - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
        - JAEGER_AGENT_HOST=tempo
        - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
        - JAEGER_SAMPLER_TYPE=const
        - JAEGER_SAMPLER_PARAM=1
  prometheus:
    image: prom/prometheus
    extra_hosts: ['host.docker.internal:host-gateway']
    networks: 
        - microservices-net
    command:
        - --enable-feature=exemplar-storage
        - --config.file=/etc/prometheus/prometheus.yml
    volumes:
        - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
        - "9090:9090"
  grafana:
    image: grafana/grafana
    extra_hosts: ['host.docker.internal:host-gateway']
    networks: 
        - microservices-net
    volumes:
        - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
        - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
        - "3000:3000"
  config-server:
    build: ./microservice-config-server
    extra_hosts: ['host.docker.internal:host-gateway']
    networks:
      - microservices-net
    ports:
      - "8888:8888"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8888/actuator/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  service-registry-server:
    build: ./microservice-registry-service
    extra_hosts: ['host.docker.internal:host-gateway']
    networks:
      - microservices-net
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "8761:8761"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  api-gateway-server:
    build: ./microservice-api-gateway
    extra_hosts: ['host.docker.internal:host-gateway']
    networks:
      - microservices-net
    depends_on:
      keycloak:
        condition: service_started
      config-server:
        condition: service_healthy
      service-registry-server:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/actuator/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  user-service:
    build: ./microservice-user-service
    extra_hosts: ['host.docker.internal:host-gateway']
    networks:
      - microservices-net
    depends_on:
      config-server:
        condition: service_healthy
      service-registry-server:
        condition: service_healthy
      mongodb:
        condition: service_started
      loki:
        condition: service_started
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8083/userService/actuator/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8083:8083"
  user-notes-service:
    build: ./microservice-usernotes-service
    extra_hosts: ['host.docker.internal:host-gateway']
    networks:
      - microservices-net
    depends_on:
      config-server:
        condition: service_healthy
      service-registry-server:
        condition: service_healthy
      mongodb:
        condition: service_started
      loki:
        condition: service_started
    ports:
      - "8084:8084"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8084/userNotes/actuator/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3