global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: 'userService'
      metrics_path: 'userService/actuator/prometheus'
      static_configs:
        - targets: ['10.0.2.2:8083']
    - job_name: 'userNotes'
      metrics_path: 'userNotes/actuator/prometheus'
      static_configs:
        - targets: ['10.0.2.2:8084']