global:
    scrape_interval: 30s
    evaluation_interval: 30s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: 'User Service'
      metrics_path: 'userService/actuator/prometheus'
      static_configs:
        - targets: ['user-service:8083']
    - job_name: 'User Notes'
      metrics_path: 'userNotes/actuator/prometheus'
      static_configs:
        - targets: ['user-notes-service:8084']
    - job_name: 'Service Discovery'
      metrics_path: 'actuator/prometheus'
      static_configs:
        - targets: [ 'service-registry-server:8761']
    - job_name: 'API Gateway'
      metrics_path: 'actuator/prometheus'
      static_configs:
        - targets: [ 'api-gateway-server:8081' ]